version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./logs:/var/log/nginx
    networks:
      nginx_net:
        ipv4_address: 172.20.8.10

networks:
  nginx_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.8.0/24
          gateway: 172.20.8.1
